_wandb:
    value:
        cli_version: 0.25.0
        e:
            zrni0jlysxlqhpoanwmuxcq8oxvgn9fq:
                args:
                    - --config
                    - config/MultiVSL200/train_bone_motion.yaml
                    - --clone_auto
                    - "True"
                    - --evolve_mode
                    - "True"
                    - --use-wandb
                    - "True"
                    - --wandb-project
                    - HA-SLR-CEGCN
                    - --wandb-run-name
                    - MultiVSL200_BoneMotion_Evolve
                codePath: Code/Network/SL_GCN/main_base.py
                codePathLocal: main_base.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "243885932544"
                        used: "179559194624"
                email: ibme.lab@gmail.com
                executable: /mnt/nvme0/home/utbt_sv1/miniconda3/envs/haslr_env/bin/python
                git:
                    commit: 37519571830155894ac9a3ac6827ee2e8661963c
                    remote: https://github.com/KILIAN0802/HA-SLR.git
                gpu: NVIDIA RTX 4500 Ada Generation
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7680
                      memoryTotal: "25763512320"
                      name: NVIDIA RTX 4500 Ada Generation
                      uuid: GPU-5f1f959d-3379-a292-8ee1-85d75013615e
                    - architecture: Ada
                      cudaCores: 7680
                      memoryTotal: "25763512320"
                      name: NVIDIA RTX 4500 Ada Generation
                      uuid: GPU-e676f2a2-a788-d122-d48d-ed8b24dca2c5
                    - architecture: Ada
                      cudaCores: 7680
                      memoryTotal: "25763512320"
                      name: NVIDIA RTX 4500 Ada Generation
                      uuid: GPU-41fabe21-d274-4031-8bb3-b94752bfacac
                    - architecture: Ada
                      cudaCores: 7680
                      memoryTotal: "25763512320"
                      name: NVIDIA RTX 4500 Ada Generation
                      uuid: GPU-ec79787f-1ec3-e7be-a6de-2ddcb610d79e
                host: sigm-UTBT
                memory:
                    total: "67132579840"
                os: Linux-6.14.0-33-generic-x86_64-with-glibc2.39
                program: /mnt/nvme2/users/utbt_sv1/HASLR/HA-SLR/Code/Network/SL_GCN/main_base.py
                python: CPython 3.10.20
                root: /mnt/nvme2/users/utbt_sv1/HASLR/HA-SLR/Code/Network/SL_GCN
                startedAt: "2026-05-19T16:06:19.128181Z"
                writerId: zrni0jlysxlqhpoanwmuxcq8oxvgn9fq
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 61
            "4": 3.10.20
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
Experiment_name:
    value: MultiVSL200/Bone_Motion
auto_resume:
    value: false
base_lr:
    value: 0.1
batch_size:
    value: 32
clone_auto:
    value: true
config:
    value: config/MultiVSL200/train_bone_motion.yaml
device:
    value:
        - 0
es:
    value: false
es_patience:
    value: 50
eval_interval:
    value: 5
eval_pkl:
    value: null
evolve_mode:
    value: true
feeder:
    value: feeders.feeder_cvpr.Feeder
groups:
    value: 8
ignore_weights:
    value: []
joint_sign:
    value: processed
joint_type:
    value: 27_direct
keep_rate:
    value: 0.9
log_interval:
    value: 100
modality:
    value: joint
model:
    value: model.hand_aware_sl_lgcn.Model
model_args:
    value:
        A_hands: graph.sign_27_A_hands.Graph
        graph: graph.sign_27.Graph
        graph_args:
            labeling_mode: spatial
        num_class: 200
        num_person: 1
        num_point: 27
model_saved_name:
    value: ./work_dir/MultiVSL200/Bone_Motion/bs32_f150_lr0.1_warmup0/2026-05-19_23-06-18/checkpoints/Bone_Motion
nesterov:
    value: false
num_epoch:
    value: 200
num_worker:
    value: 0
only_train_epoch:
    value: 0
only_train_part:
    value: true
optimizer:
    value: SGD
phase:
    value: train
pretrain_cpt_time_tag:
    value: '*'
print_log:
    value: true
resume_checkpoint:
    value: ""
save_interval:
    value: 2
save_score:
    value: false
seed:
    value: 1
show_topk:
    value:
        - 1
        - 5
splits:
    value:
        - test
start_epoch:
    value: 0
step:
    value:
        - 50
        - 100
        - 150
test_base_lr:
    value: 0.1
test_batch_size:
    value: 256
test_feeder_args:
    value:
        data_path: data/data/Thi/processed/27_direct/test_data_bone_motion.npy
        debug: false
        label_path: data/data/Thi/processed/27_direct/test_label.pkl
        window_size: 150
train_base_lr:
    value: 0.1
train_feeder_args:
    value:
        data_path: data/data/Thi/processed/27_direct/train_data_bone_motion.npy
        debug: false
        label_path: data/data/Thi/processed/27_direct/train_label.pkl
        use_jdma: true
        window_size: 150
use_wandb:
    value: true
val_feeder_args:
    value:
        data_path: data/data/Thi/processed/27_direct/val_data_bone_motion.npy
        debug: false
        label_path: data/data/Thi/processed/27_direct/val_label.pkl
        window_size: 150
wandb_entity:
    value: ""
wandb_group:
    value: ""
wandb_id:
    value: ""
wandb_mode:
    value: online
wandb_project:
    value: HA-SLR-CEGCN
wandb_resume:
    value: auto
wandb_run_name:
    value: MultiVSL200_BoneMotion_Evolve
wandb_tags:
    value: []
warm_up_epoch:
    value: 0
weight_decay:
    value: 0.0005
weights:
    value: null
work_dir:
    value: ./work_dir/MultiVSL200/Bone_Motion/bs32_f150_lr0.1_warmup0/2026-05-19_23-06-18
