Experiment_name: AUTSL/Joint/autsl_joint_27_cvpr_hand_aware_sl_lgcn_baseline
base_lr: 0.1
batch_size: 64
config: config/sign_cvpr_A_hands/AUTSL/train_joint_autsl.yaml
device:
- 0
es: false
es_patience: 50
eval_interval: 5
eval_pkl: null
feeder: feeders.feeder_cvpr.Feeder
groups: 8
ignore_weights: []
keep_rate: 0.9
log_interval: 100
model: model.hand_aware_sl_lgcn.Model
model_args:
  A_hands: graph.sign_27_A_hands.Graph
  block_size: 41
  graph: graph.sign_27_cvpr.Graph
  graph_args:
    labeling_mode: spatial
  groups: 16
  num_class: 226
  num_person: 1
  num_point: 27
model_saved_name: ./work_dir\AUTSL/Joint/autsl_joint_27_cvpr_hand_aware_sl_lgcn_baseline/bs64_f100_lr0.1_warmup20/2026-04-07_17-42-59\checkpoints\autsl_joint_27_cvpr_hand_aware_sl_lgcn_baseline
nesterov: true
num_epoch: 500
num_worker: 32
only_train_epoch: 1
only_train_part: true
optimizer: SGD
phase: train
print_log: true
save_interval: 2
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 150
- 200
test_base_lr: 0.1
test_batch_size: 64
test_feeder_args:
  data_path: ./data/sign_autsl/27_cvpr/test_data_joint.npy
  debug: false
  label_path: ./data/sign_autsl/27_cvpr/test_label.pkl
  normalization: true
  random_mirror: false
train_base_lr: 0.1
train_feeder_args:
  data_path: ./data/sign_autsl/27_cvpr/train_data_joint.npy
  debug: false
  is_vector: false
  label_path: ./data/sign_autsl/27_cvpr/train_label.pkl
  normalization: true
  random_choose: true
  random_mirror: true
  random_mirror_p: 0.5
  random_shift: true
  window_size: 100
val_feeder_args:
  data_path: ./data/sign_autsl/27_cvpr/val_data_joint.npy
  debug: false
  label_path: ./data/sign_autsl/27_cvpr/val_label.pkl
  normalization: true
  random_mirror: false
warm_up_epoch: 20
weight_decay: 0.0001
weights: null
work_dir: ./work_dir\AUTSL/Joint/autsl_joint_27_cvpr_hand_aware_sl_lgcn_baseline/bs64_f100_lr0.1_warmup20/2026-04-07_17-42-59
